######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 28 20:37:44 2010
######################################################################

TEMPLATE = app
QT += network gui
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
INCLUDEPATH += ../libgroove/

# Input
SOURCES += main.cpp \
    mainwindow.cpp

LIBS += ../libgroove-build-desktop/libgroove.so

HEADERS += \
    mainwindow.h

FORMS += \
    mainwindow.ui
